[development]
address = "localhost"
port = 30443

[global.databases]
diesel_postgres_pool = { url = "postgres://shin:shinglish@localhost/diesel_demo" }

[global.tls]
certs = "private/cert.pem"
key = "private/key.pem"
